config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, { defaults: { format: :json } } do
    namespace :v1 do
      resources :recipes, only: %i[index show create update destroy]
    end
  end
  resources :recipe_ingredients
  resources :recipes
  resources :ingredients
  resources :plannings do
    resources :planning_recipes, on: :member
  end

  root "recipes#index"
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_and_belongs_to_many :planning_recipes, dependent: :nullify, join_table: "planning_recipes"
  has_and_belongs_to_many :plannings, through: :planning_recipes, join_table: "planning_recipes"

  accepts_nested_attributes_for :recipe_ingredients
end

app/controllers/api/v1/recipes_controller.rb
# frozen_string_literal: true

class Api::V1::RecipesController < Api::V1::ApiController
  before_action :set_recipe, only: %i[show update destroy]

  def index
    @recipes = Recipe.all.order(name: :asc)
  end

  def show; end

  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.json { render :show, status: :created, location: @recipe }
      else
        format.json { render_error(:unprocessable_entity, @recipe.errors) }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.json { render_error(:unprocessable_entity, @recipe.errors) }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description)
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all.order("LOWER(name) ASC")
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
    @ingredients_not_in_recipe = Ingredient.not_in_recipe(@recipe.id)
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_url, notice: "#{@recipe.name} was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipes_url, notice: "#{@recipe.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name,
                                   recipe_ingredients_attributes: %i[ingredient_id recipe_id quantity id
                                                                     ingredient_unit_id])
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/views/recipes/_add_ingredients.html.erb
<h1 class="text-2xl font-bold text-center mt-8">Add Ingredients</h1>
    <%= turbo_frame_tag "unused_ingredients_turbo_frame" do %>
        <div class="flex flex-wrap gap-2" id="unused_ingredients">
            <% ingredients&.each do |ingredient| %>
                <%= render 'unused_ingredient', ingredient: ingredient, recipe_id: %>
            <% end %>
        </div>
    <% end %>
<%= render 'ingredients/form', ingredient: Ingredient.new, recipe_id: %>

app/views/recipes/_form.html.erb
<div class="flex flex-col gap-5">
  <%= form_with(model: recipe, id: 'recipe_form', data: {turbo: true}) do |form| %>
    <% if recipe.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

        <ul>
          <% recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="flex flex-col gap-8">
      <div class="flex items-center gap-2">
        <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 w-full" %>
        <%= form.submit "Save", class: "rounded-lg bg-blue-600 text-white p-2 min-w-32" %>
        <% if params[:action] == 'edit' %>
          <%= link_to "Delete", recipe_path(recipe), data: { turbo: true, turbo_method: :delete },
          class: "rounded-lg bg-red-500 text-white p-2 min-w-32 flex justify-center" %>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= turbo_frame_tag "included_ingredients_turbo_frame" do %>
    <div class="flex flex-col gap-2" id="used_ingredients">
      <% recipe.recipe_ingredients.each do |recipe_ingredient| %>
        <%= render 'ingredient_form', recipe_ingredient: %>
      <% end %>
    </div>
  <% end%>
  <%= render "add_ingredients", ingredients: @ingredients_not_in_recipe, recipe_id: recipe.id%>
</div>

app/views/recipes/_included_ingredients.html.erb
<% @recipe.recipe_ingredients.order(:id).each do |recipe_ingredient| %>
  <%= turbo_stream_from "recipe_ingredient_#{recipe_ingredient.id}" %>
  <%= turbo_frame_tag dom_id(recipe_ingredient), class: 'flex justify-between gap-2 w-full items-center py-1' do %>
    <%= render 'included_ingredient', recipe_ingredient: recipe_ingredient %>
  <% end %>
<% end %>

app/views/recipes/_ingredient_form.html.erb
<div class="flex w-1/2 justify-start gap-3 items-center" id=<%= dom_id(recipe_ingredient) %>>
<%= form_with(model: recipe_ingredient, data: { turbo: true }) do |form| %>
    <div class="grid grid-cols-4 items-center gap-3">
        <% quantities = ['1/4', '1/2', '3/4', '1', '1.5', '2', '3', '4', '5', '6', '7', '8', '9', '10'] %>
        <p class="col-span-2 text-wrap break-all"><%= recipe_ingredient.ingredient.name %></p>
        <%= form.select :quantity, quantities.map { |fraction| [fraction, fraction_to_float(fraction)] },
        { selected: recipe_ingredient.quantity.to_s, include_blank: true }, { onchange: "submitForm(this.form)" } %>
        <%= form.collection_select :ingredient_unit_id , IngredientUnit.all, :id, :name, { include_blank: true },
            { onchange: "submitForm(this.form)" } %>
    </div>
<% end %>
<%= button_to recipe_ingredient_path(recipe_ingredient), method: :delete do %>
    <i class="fas fa-trash text-red-500"></i>
<% end %>
</div>

<script>
function submitForm(form) {
    form.submit();
}
</script>

app/views/recipes/_recipe.html.erb
<%= link_to edit_recipe_path(recipe), class: "w-full" do %>
  <div id="<%= dom_id recipe %>", class="border border-blue-500 border-2 bg-neutral-300 rounded-xl mt-2">
    <p class="text-2xl text-wrap break-normal overflow-hidden truncate p-2"><%= recipe.name %></p>
    <hr class="border-t-2 border-blue-500">
    <div class="flex flex-col p-2">
      <% recipe.ingredients.order(:name).each do |ingredient| %>
        <p class="text-wrap break-normal overflow-hidden truncate"><%= ingredient.name %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/_unused_ingredient.html.erb
<%= button_to recipe_ingredients_path(recipe_ingredient: {ingredient_id: ingredient.id, recipe_id:},
    id: "unused_ingrdient_#{ingredient.id}") do %>
    <div class="flex justify-between gap-4 border border-black rounded-xl p-2", id=<%= "unused_ingredient_#{ingredient.id}" %>>
        <p class="text-wrap break-normal overflow-hidden truncate"><%= ingredient.name %></p>
    </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render "form", recipe: @recipe %>

app/views/recipes/edit2.html.erb
<%= form_with(model: @recipe, data: { turbo: true }) do |form| %>
  <div class="mx-auto md:w-2/3 w-full flex flex-col" id="edit_recipe">
    <%= render "form", recipe: @recipe %>
    <div class="flex my-5 justify-between gap-8">
      <%= turbo_frame_tag 'included_ingredients', class: 'w-3/4' do %>
        <div class="flex flex-col" id="included_ingredients">
          <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
            <%= render 'included_ingredient', recipe_ingredient: %>
          <% end %>
        </div>
      <% end %>
      <div class="flex flex-col w-1/4">
        <%= turbo_frame_tag 'unused_ingredients' do %>
          <div class="flex flex-col" id="unused_ingredients">
            <% @ingredients_not_in_recipe.each do |ingredient| %>
              <%= render 'unused_ingredient', ingredient:, recipe_id: @recipe.id %>
            <% end %>
          </div>
        <% end %>
        <div class="my-2 w-full">
          <%= render 'ingredients/form', ingredient: Ingredient.new %>
        </div>
      </div>
    </div>
    <%= form.submit "Save Recipe" %>
  </div>
<% end %>

<script>
  document.addEventListener("turbo:submit-end", function(event) {
    if (event.target.matches("[id='edit_recipe']")) {
      debugger;
      document.querySelectorAll("#included_ingredients form").forEach(function(form) {
        form.requestSubmit();
      });
    }
  });
</script>

app/views/recipes/index.html.erb
<div class="w-full flex flex-col gap-4 items-center">
  <div class="text-4xl justify-center my-2">Your Recipes</div>
  <div class="flex justify-between items-center">
    <%= link_to "Add A Recipe", new_recipe_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="recipes" class="min-w-full grid grid-cols-3 gap-2">
    <%= render @recipes %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to "Back to recipes", recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @recipe %>

    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this recipe", recipe_path(@recipe), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to recipes", recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/recipes/update.turbo_stream.erb
<%= turbo_stream.replace "included_ingredients", partial: "included_ingredients" %>