config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, { defaults: { format: :json } } do
    namespace :v1 do
      resources :recipes, only: %i[index show create update destroy]
    end
  end
  resources :recipe_ingredients
  resources :recipes
  resources :ingredients
  resources :plannings do
    resources :planning_recipes, on: :member
  end

  root "recipes#index"
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients

  scope :not_in_recipe, lambda { |recipe_id|
    where.not(id: RecipeIngredient.select(:ingredient_id).where(recipe_id:))
  }
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  # POST /ingredients or /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params.except(:recipe_id))

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to ingredients_url, notice: "Ingredient was successfully created." }
        format.turbo_stream do
          render turbo_stream: turbo_stream.append("unused_ingredients_turbo_frame", partial: "unused_ingredients",
                                                                                     locals: { ingredient: @ingredient,
                                                                                               recipe: Recipe.find(params[:recipe_id]) })
        end
        format.json { render :index, status: :created, location: @ingredient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1 or /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: "Ingredient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def ingredient_params
    params.require(:ingredient).permit(:name, :recipe_id)
  end
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, class: "contents", data: { turbo: true }) do |form| %>
  <% form.hidden_field :recipe_id, value: recipe_id %>
  <div class="flex w-full">
    <% if ingredient.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

        <ul>
          <% ingredient.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="flex w-full gap-2">
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200  outline-none w-full" %>
      <button type='submit'>
        <i class="fa-solid fa-plus text-green-500"></i>
      </button>
    </div>
  </div>
<% end %>

app/views/ingredients/_ingredient.html.erb
<% delete_path = params[:controller] == 'ingredients' ? ingredient_path(ingredient) : recipe_ingredient_path(ingredient) %>
<div class="border border-blue-500 rounded-xl p-2 gap-1 flex justify-between">
  <p class="text-wrap break-normal overflow-hidden truncate"><%= ingredient.name %></p>
  <%= button_to delete_path, method: :delete do %>
    <i class="fas fa-trash"></i>
  <% end %>
</div>