config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api, { defaults: { format: :json } } do
    namespace :v1 do
      resources :recipes, only: %i[index show create update destroy]
    end
  end
  resources :recipe_ingredients
  resources :recipes
  resources :ingredients
  resources :plannings do
    resources :planning_recipes, on: :member
  end

  root "recipes#index"
end

app/models/planning.rb
class Planning < ApplicationRecord
  has_many :planning_recipes
  has_many :recipes, through: :planning_recipes
end

app/controllers/plannings_controller.rb
# frozen_string_literal: true

class PlanningsController < ApplicationController
  before_action :set_planning, except: %i[ create ]

  def create
    @recipes = Recipe.includes(recipe_ingredients: :ingredient_unit).all.sample(7)
    @planning = Planning.new
    @recipes.each do |recipe|
      @planning.recipes << recipe
    end

    respond_to do |format|
      if @planning.save
        format.html { redirect_to edit_planning_path(@planning) }
        format.json { render json: @planning }
      else
        format.html { redirect_to root_path, notice: { error: "There was an error creating your plan. Please try again." } }
        format.json { render json: @planning.errors }
      end
    end
  end

  def edit; end

  def show
    @ingredients = @planning.recipes.includes(:ingredients).map(&:recipe_ingredients).flatten.group_by(&:ingredient_id)
                            .map do |ingredient_id, recipe_ingredients|
      readable_ingredient = convert_to_readable_unit(recipe_ingredients)
      {
        name: Ingredient.find(ingredient_id).name,
        quantity: readable_ingredient[:quantity],
        unit: readable_ingredient[:unit]
      }
    end
  end

  private

  def set_planning
    @planning = Planning.find(params[:id])
  end

  def planning_params
    params.require(:planning).permit(recipe_ids: [])
  end

  def convert_to_base_unit(recipe_ingredients)
    total_quantity = 0
    recipe_ingredients.each do |recipe_ingredient|
      if recipe_ingredient.ingredient_unit.present?
        total_quantity += (recipe_ingredient.quantity * recipe_ingredient.ingredient_unit.base_conversion)
      end
    end

    total_quantity
  end

  def convert_to_readable_unit(recipe_ingredients)
    total_quantity = convert_to_base_unit(recipe_ingredients)
    return { quantity: total_quantity, unit: 'Units' } unless recipe_ingredients.first.ingredient_unit.present?

    type = recipe_ingredients.first.ingredient_unit.type
    options = IngredientUnit.where(type:).order(base_conversion: :desc)
    options.each do |option|
      if total_quantity > option.base_conversion
        return { quantity: (total_quantity / option.base_conversion).round(2), unit: option.name }
      end
    end

    { quantity: total_quantity, unit: 'Units' }
  end

end

app/helpers/planning_helper.rb
module PlanningHelper
end

app/views/plannings/_grocery_list_item.html.erb
<button data-controller="grocery-list-item" class="border border-black p-2 w-fit">
    <div data-grocery-list-item-target="container" class="flex items-center gap-5 w-full text-xl">
        <p><%= name %></p>
        <p><%= quantity %> <%= unit %></p>
    </div>
</button>

app/views/plannings/_recipe_card.html.erb
<%= turbo_frame_tag "recipe_card_#{dom_id recipe}", class: 'w-full' do %>
  <div id="<%= dom_id recipe %>" class="w-full border border-blue-500 bg-blue-200 border-2 bg-neutral-300 rounded-xl mt-2">
    <div class="flex p-2 justify-between">
      <p class="text-2xl text-wrap break-normal overflow-hidden truncate p-2"><%= recipe.name %></p>
      <%= button_to planning_planning_recipe_path(@planning, @planning.planning_recipes.find_by(recipe_id: recipe.id)),
                    method: :patch do %>
        <i class="fas fa-refresh"></i>
      <% end %>
    </div>
    <hr class="border-t-2 border-blue-500">
    <div class="flex flex-col p-2">
      <% recipe.ingredients.order(:name).each do |ingredient| %>
        <p class="text-wrap break-normal overflow-hidden truncate"><%= ingredient.name %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/plannings/edit.html.erb
<% days = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday] %>
<div class="flex flex-col items-center gap-5">
  <p class="text-4xl">Weekly Plan</p>
  <% @planning.recipes.each do |recipe| %>
    <%= render 'recipe_card', recipe: recipe %>
  <% end %>
  <div class="flex flex-col border border-2 w-full gap-2 p-2">
    <% @planning.recipes.each_with_index do |recipe, i| %>
      <p><%= "#{days[i]} : #{recipe.name}" %></p>
    <% end %>
  </div>
  <%= link_to "View Grocery List", planning_path(@planning),
              class: 'border border-2 p-2 bg-blue-300 border-blue-500 rounded-2xl' %>
</div>

app/views/plannings/show.html.erb
<div class="flex flex-col items-center gap-5">
    <p class="text-2xl">Grocery List</p>
    <% @ingredients.each do |ingredient| %>
        <%= render 'grocery_list_item', name: ingredient[:name], quantity: ingredient[:quantity], unit: ingredient[:unit] %>
    <% end %>
</div>